# Generated by Django 5.0.14 on 2026-10-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_email_code_user_email_code_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="reset_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="reset_code_created",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
