# Generated by Django 5.0.14 on 2026-09-08 21:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="added_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата добавления",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="finished_reading",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата окончания чтения"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Заметки"),
        ),
        migrations.AddField(
            model_name="book",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="pages",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Количество страниц"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Оценка от 1 до 5",
                null=True,
                verbose_name="Оценка",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="reading_status",
            field=models.CharField(
                choices=[
                    ("not_started", "Не начата"),
                    ("in_progress", "В процессе"),
                    ("finished", "Прочитана"),
                    ("abandoned", "Отложена"),
                ],
                default="not_started",
                max_length=20,
                verbose_name="Статус чтения",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="started_reading",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата начала чтения"
            ),
        ),
    ]
