# Generated by Django 5.0.14 on 2026-09-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_book_added_at_book_finished_reading_book_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="pages",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="published_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
