# Generated by Django 5.0.14 on 2026-10-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_author_owner_alter_book_pages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="reading_status",
            field=models.CharField(
                choices=[
                    ("not_started", "Не начата"),
                    ("in_progress", "В процессе"),
                    ("finished", "Прочитана"),
                    ("abandoned", "Отложена"),
                    ("want_to_buy", "Хочу купить"),
                ],
                default="not_started",
                max_length=20,
                verbose_name="Статус чтения",
            ),
        ),
    ]
